### ISSUE TITLE
Environment installation problem

### ISSUE THREAD

**Issue by GendalfSeriyy** [andreagemelli/doc2graph#12]
Hi! Thank you for repo!
I have a problem installing dependencies. Could you help solve this?
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dglgo 0.0.2 requires pydantic>=1.9.0, but you have pydantic 1.8.2 which is incompatible.
```
And when i run scripts:
```
Traceback (most recent call last):
  File "/home/addudkin/doc2graph/doc2graph/src/main.py", line 4, in <module>
    from src.inference import inference
  File "/home/addudkin/doc2graph/doc2graph/src/inference.py", line 7, in <module>
    from src.data.feature_builder import FeatureBuilder
  File "/home/addudkin/doc2graph/doc2graph/src/data/feature_builder.py", line 3, in <module>
    import spacy
  File "/home/addudkin/miniconda3/envs/doc2graph/lib/python3.9/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/home/addudkin/miniconda3/envs/doc2graph/lib/python3.9/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/home/addudkin/miniconda3/envs/doc2graph/lib/python3.9/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 8, in init spacy.pipeline.pipe
  File "/home/addudkin/miniconda3/envs/doc2graph/lib/python3.9/site-packages/spacy/training/__init__.py", line 11, in <module>
    from .callbacks import create_copy_from_base_model  # noqa: F401
  File "/home/addudkin/miniconda3/envs/doc2graph/lib/python3.9/site-packages/spacy/training/callbacks.py", line 3, in <module>
    from ..language import Language
  File "/home/addudkin/miniconda3/envs/doc2graph/lib/python3.9/site-packages/spacy/language.py", line 25, in <module>
    from .training.initialize import init_vocab, init_tok2vec
  File "/home/addudkin/miniconda3/envs/doc2graph/lib/python3.9/site-packages/spacy/training/initialize.py", line 14, in <module>
    from .pretrain import get_tok2vec_ref
  File "/home/addudkin/miniconda3/envs/doc2graph/lib/python3.9/site-packages/spacy/training/pretrain.py", line 16, in <module>
    from ..schemas import ConfigSchemaPretrain
  File "/home/addudkin/miniconda3/envs/doc2graph/lib/python3.9/site-packages/spacy/schemas.py", line 216, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 451, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 545, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 550, in pydantic.fields.ModelField._type_analysis
  File "/home/addudkin/miniconda3/envs/doc2graph/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```
My packages:
[my_requirements.txt](https://github.com/andreagemelli/doc2graph/files/11833756/my_requirements.txt)

**Comment by enricivi** [comment]
Hello,

Sorry for the late reply.

Did you already try to strictly follow the steps described in the README?

**Comment by rubenaros** [comment]
Hi, Try
 Pydantic== 1.9.2
spacy== 3.4.0
typing_extensions==4.4.0

**Comment by vvv-tech** [comment]
@rubenaros thanks, worked. I've also needed to install opencv-python==4.5.5.64
